name: flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Network & Data (Versi Stabil & Kompatibel)
  dio: ^5.4.3
  retrofit: 4.1.0 # Kita kunci di 4.1.0 agar aman
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.0.0
  logger: ^2.3.0
  shared_preferences: ^2.5.4
  simple_barcode_scanner: ^0.4.0
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generator (Kombinasi Emas)
  build_runner: ^2.4.9
  retrofit_generator: 8.1.0 # Pasangan sejati Retrofit 4.x
  json_serializable: ^6.8.0 # Versi ini paling jarang error dengan analyzer

flutter:
  uses-material-design: true
  assets:
    - assets/images/
